/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintKitIdRouteImport } from './routes/print.$kitId'
import { Route as AppVersionsRouteImport } from './routes/_app.versions'
import { Route as AppVersionLibraryRouteImport } from './routes/_app.version-library'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppQcRouteImport } from './routes/_app.qc'
import { Route as AppPrintPreviewRouteImport } from './routes/_app.print-preview'
import { Route as AppMapperRouteImport } from './routes/_app.mapper'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppBuilderRouteImport } from './routes/_app.builder'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintKitIdRoute = PrintKitIdRouteImport.update({
  id: '/print/$kitId',
  path: '/print/$kitId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVersionsRoute = AppVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AppRoute,
} as any)
const AppVersionLibraryRoute = AppVersionLibraryRouteImport.update({
  id: '/version-library',
  path: '/version-library',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppQcRoute = AppQcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintPreviewRoute = AppPrintPreviewRouteImport.update({
  id: '/print-preview',
  path: '/print-preview',
  getParentRoute: () => AppRoute,
} as any)
const AppMapperRoute = AppMapperRouteImport.update({
  id: '/mapper',
  path: '/mapper',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof AppBuilderRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/mapper': typeof AppMapperRoute
  '/print-preview': typeof AppPrintPreviewRoute
  '/qc': typeof AppQcRoute
  '/templates': typeof AppTemplatesRoute
  '/version-library': typeof AppVersionLibraryRoute
  '/versions': typeof AppVersionsRoute
  '/print/$kitId': typeof PrintKitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof AppBuilderRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/mapper': typeof AppMapperRoute
  '/print-preview': typeof AppPrintPreviewRoute
  '/qc': typeof AppQcRoute
  '/templates': typeof AppTemplatesRoute
  '/version-library': typeof AppVersionLibraryRoute
  '/versions': typeof AppVersionsRoute
  '/print/$kitId': typeof PrintKitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/builder': typeof AppBuilderRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import': typeof AppImportRoute
  '/_app/mapper': typeof AppMapperRoute
  '/_app/print-preview': typeof AppPrintPreviewRoute
  '/_app/qc': typeof AppQcRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/version-library': typeof AppVersionLibraryRoute
  '/_app/versions': typeof AppVersionsRoute
  '/print/$kitId': typeof PrintKitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/create'
    | '/dashboard'
    | '/import'
    | '/mapper'
    | '/print-preview'
    | '/qc'
    | '/templates'
    | '/version-library'
    | '/versions'
    | '/print/$kitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/create'
    | '/dashboard'
    | '/import'
    | '/mapper'
    | '/print-preview'
    | '/qc'
    | '/templates'
    | '/version-library'
    | '/versions'
    | '/print/$kitId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/builder'
    | '/_app/create'
    | '/_app/dashboard'
    | '/_app/import'
    | '/_app/mapper'
    | '/_app/print-preview'
    | '/_app/qc'
    | '/_app/templates'
    | '/_app/version-library'
    | '/_app/versions'
    | '/print/$kitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrintKitIdRoute: typeof PrintKitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$kitId': {
      id: '/print/$kitId'
      path: '/print/$kitId'
      fullPath: '/print/$kitId'
      preLoaderRoute: typeof PrintKitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/versions': {
      id: '/_app/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof AppVersionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/version-library': {
      id: '/_app/version-library'
      path: '/version-library'
      fullPath: '/version-library'
      preLoaderRoute: typeof AppVersionLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qc': {
      id: '/_app/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof AppQcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print-preview': {
      id: '/_app/print-preview'
      path: '/print-preview'
      fullPath: '/print-preview'
      preLoaderRoute: typeof AppPrintPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapper': {
      id: '/_app/mapper'
      path: '/mapper'
      fullPath: '/mapper'
      preLoaderRoute: typeof AppMapperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builder': {
      id: '/_app/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuilderRoute: typeof AppBuilderRoute
  AppCreateRoute: typeof AppCreateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportRoute: typeof AppImportRoute
  AppMapperRoute: typeof AppMapperRoute
  AppPrintPreviewRoute: typeof AppPrintPreviewRoute
  AppQcRoute: typeof AppQcRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppVersionLibraryRoute: typeof AppVersionLibraryRoute
  AppVersionsRoute: typeof AppVersionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuilderRoute: AppBuilderRoute,
  AppCreateRoute: AppCreateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportRoute: AppImportRoute,
  AppMapperRoute: AppMapperRoute,
  AppPrintPreviewRoute: AppPrintPreviewRoute,
  AppQcRoute: AppQcRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppVersionLibraryRoute: AppVersionLibraryRoute,
  AppVersionsRoute: AppVersionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrintKitIdRoute: PrintKitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
